### ISSUE TITLE
ERROR when running Joint Inference model

### ISSUE THREAD

**Issue by bensuucar** [xcyan/neurips18_hierchical_image_manipulation#7]
I dowloaded pretrained model for city dataset and when I try to run Joint Inference, it cannot find 'network' in self.netG.params_dict. 

I have the following error;

Traceback (most recent call last):
  File "vis_joint_inference.py", line 30, in <module>
    joint_inference_model = JointInference(joint_opt)
  File "/data/Bensu/Models/neurips18_hierchical_image_manipulation-master/models/joint_inference_model.py", line 28, in __init__
    self.G_box2mask = create_model(self.opt_maskgen)
  File "/data/Bensu/Models/neurips18_hierchical_image_manipulation-master/models/models.py", line 9, in create_model
    model = TwoStreamAE_mask(opt)
  File "/data/Bensu/Models/neurips18_hierchical_image_manipulation-master/models/TwoStreamAE_mask.py", line 119, in __init__
    self.netG.params_dict, None, 'G', opt.which_epoch, '')
  File "/data/Bensu/Models/neurips18_hierchical_image_manipulation-master/models/base_model.py", line 122, in load_network_dict
    v.load_state_dict(checkpoint['network'][k])
KeyError: 'network'

Is it because I try it with pre-trained networks?Could you please help me to find where the error comes from?

**Comment by xcyan** [comment]
@bensuucar Can you possibly put a breakpoint (import pdb; pdb.set_trace()) at the following line and print out the "checkpoint" or "dir(checkpoint)"? Thank you!

https://github.com/xcyan/neurips18_hierchical_image_manipulation/blob/master/models/base_model.py#L119
